remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Google Takeout Metadata Fixer
description: matches your .JSON metadata to your partner IMG/VIDEO files
show_downloads: true
